services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mysql://albarkaschool:tacheyon5567@localhost:3306/albarkaschool
    develop:
      # specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container and image if there are any changes
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /school-server
          action: sync
    network_mode: "host"
    volumes:
      - db-data:/db/

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    develop:
      # we specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: ./frontend
          target: /school-client
          action: sync
volumes:
  db-data:
