services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
       NEXT_PUBLIC_SERVER_API: "https://schoolbackend.tacheyon.com/api"
    depends_on:
      - backend
