import express from "express";
import { config } from "dotenv";
import cors from "cors";
import auth from "./routes/auth.js";
import accounts from "./routes/accounts.js";
import backup from "./routes/backup.js";
import appointments from "./routes/appointments.js";
import subjects from "./routes/subjects.js";
import feesgroup from "./routes/feesgroup.js";
import classes from "./routes/classes.js";
import payments from "./routes/payments.js";
import transactions from "./routes/transactions.js";
import promotions from "./routes/promotions.js";
import demotions from "./routes/demotions.js";
import staffs from "./routes/staffs.js";
import students from "./routes/students.js";
import fca from "./routes/fca.js";
import sca from "./routes/sca.js";
import exams from "./routes/exams.js";
import statements from "./routes/statements.js";
import disengagements from "./routes/disengagements.js";
const app = express();
const port = 5000;
config();
app.use(express.json());
app.use(cors());
app.use("/api/auth", auth);
app.use("/api/appointments", appointments);
app.use("/api/subjects", subjects);
app.use("/api/feesgroup", feesgroup);
app.use("/api/accounts", accounts);
app.use("/api/backup", backup);
app.use("/api/classes", classes);
app.use("/api/payments", payments);
app.use("/api/transactions", transactions);
app.use("/api/promotions", promotions);
app.use("/api/demotions", demotions);
app.use("/api/staffs", staffs);
app.use("/api/students", students);
app.use("/api/fca", fca);
app.use("/api/sca", sca);
app.use("/api/exams", exams);
app.use("/api/statements", statements);
app.use("/api/disengagements", disengagements);
app.get("/", (req, res) => {
	res.send("<h2>Welcome</h2>");
});
app.listen(port, () => {
	console.log(`Albarka server listening on port ${port}`);
});
